version: "2"
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    volumes:
      - /svr/${PROJECT}/db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  redis:
    image: redis:3

  web:
    restart: always
    build: ./../
    image: unit6/test-${PROJECT}
    volumes:
      - /c/Projects/${PROJECT}/pm2_logs:/srv/server:rw
      - /c/Projects/${PROJECT}/project_log:/project/log:rw
      - /c/Projects/${PROJECT}/project_error:/project/error:rw
    ports:
      - "3002:80"
    depends_on:
      - db
      - redis
