version: "2"
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"

  redis:
    image: redis:3

  web:
    restart: always
    build: ./../
    image: unit6/test-server-sprout
    volumes:
      - /c/Projects/server-sprout/pm2_logs:/srv/server:rw
      - /c/Projects/server-sprout/project_log:/project/log:rw
      - /c/Projects/server-sprout/project_error:/project/error:rw
    depends_on:
      - db
      - redis
