version: "2"
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    volumes:
      - /svr/${PROJECT}/db:/var/lib/postgresql/data:rw

  redis:
    image: redis:3

  web:
    restart: always
    build: .
    image: unit6/${PROJECT}
    volumes:
      - /srv/${PROJECT}/pm2_logs:/srv/server:rw
      - /srv/${PROJECT}/project_log:/project/log:rw
      - /srv/${PROJECT}/project_error:/project/error:rw
    ports:
      - "${DOCKER_PORT}:80"
    depends_on:
      - db
      - redis
